### ISSUE TITLE
Amiga console buffering: Couldn't the end of buffer be stored instead of looping through the buffer for every character added to it

### ISSUE THREAD

**Issue by kelihlodversson** [emutos/emutos#20]
This line in amiga.c finds the end of a static buffer to append a character to it: https://github.com/emutos/emutos/blob/4f4b593948eb26a68152356369ffdae86b3c50bf/bios/amiga.c#L1322

A better way would be to store the pointer somewhere along with the buffer itself.

**Comment by vinriviere** [comment]
Indeed. My main idea was to mimic strcat(), which suffers of the same issue. As debug output is not used that much in normal situation, I didn't bother to optimize that.
