### ISSUE TITLE
Feature request: EmuCON as an accessory?

### ISSUE THREAD

**Issue by robdaemon** [emutos/emutos#30]
Would it be possible to put EmuCON in a GEM window as an accessory?

**Comment by anodynesoftware** [comment]
Not to be too glib, but (almost) everything is possible in software!  However, if you mean: "could you do that?", the answer is no, it's outside the scope of EmuTOS. If you wish to do it yourself, you can of course use the existing code as a basis as long as the resultant code is released under the GPL.

For questions like this (and indeed all questions about EmuTOS), we encourage you to join the EmuTOS mailing list and ask them there.
