### ISSUE TITLE
emutos.prg or floppy cannot be started from emutos cart

### ISSUE THREAD

**Issue by ctirad** [emutos/emutos#34]
Hello, 

neither emutos.prg nor emutos floppy can be started from emutos cart (1.2 and 1.1.1 tested). The image is loaded, but instead of initialization, everything is reset back to emutos from cart. 
Loading of TOS2.6 using seltos utility is possible, though.

**Comment by czietz** [comment]
Thank you for your report. But one could say this is by _design_: EmuTOS -- very early during the boot phase -- checks if there is a bootable cartridge. If such a cartridge is found, it is booted instead.

And this is exactly what happens: The .prg or floppy versions detect a bootable cartridge (in this case: the EmuTOS one) and boot the cartridge code instead.

Now, we could add a special case, for EmuTOS _not_ to boot a cartridge if it's an EmuTOS one. But presumably this could break other people's workflows. So I cannot do this lightly, but first have to collect opinions on the mailing list. Feel free to join the discussion there and to explain your particular use case.

**Comment by czietz** [comment]
Thank you for bringing this up and joining the discussion on the mailing list. Fixed with commit 97a1c1c.
