### ISSUE TITLE
Traders game hangs with EmuTOS

### ISSUE THREAD

**Issue by AdamKlob** [emutos/emutos#38]
Traders hangs on startup when being run with EmuTOS (192KB)

Screenshot:

![337985367_1559129844570526_7755311704102559098_n](https://user-images.githubusercontent.com/450303/231141628-2a222ce6-a0b3-462d-8273-81f2a401d9c7.png)

Links to download the game: https://www.atarilegend.com/menusets/143?page=2&fbclid=IwAR1KvI07J3GnZlszGPd5k4DZ2Q18D3zv0glrEiWdhzKCM2uoAJ5CyeG00mQ#menudisk-3102

It woks with TOS 1.62.

**Comment by czietz** [comment]
Thank you for the detailed report!

I'm afraid, though, that I cannot reproduce it. When I run `A:\TRADDATA\TRADERS.PRG` [^1] from the floppy disk mentioned above, the game does not crash. I don't know how to play it; but it certainly does start up:

![grab0037](https://user-images.githubusercontent.com/9830685/231227347-7feeb074-da43-42d8-840b-ce20affd84d0.png)
![grab0038](https://user-images.githubusercontent.com/9830685/231227369-c7f3412c-545c-424b-aa38-67a2a8b63cd0.png)
![grab0039](https://user-images.githubusercontent.com/9830685/231227390-8ed6cbc6-0a11-495a-9293-f9afa6c33b77.png)

[^1]: The AUTO loader / cracktro on the floppy has an issue though. It seems to be stuck in a loop of flashing colors. (But still no panic.) The same behavior is observed with TOS 2.06. Therefore, I don't think the cracktro issue is EmuTOS-related.

**Comment by th-otto** [comment]
I cannot reproduce it either. You can even try to run it in PCE:

[http://tho-otto.de/fatfs/fatfs.php?image=https%3A%2F%2Fwww.atarilegend.com%2Fstorage%2Fzips%2Fmenus%2F1705.zip&codepage=](url)

(then use the button "Run NOW5_22.MSA.st in PCE"):

![Screenshot_20230411_184235](https://user-images.githubusercontent.com/12425871/231232805-623641db-85c4-49b9-b5a9-75c38a42a1fe.png)

**Comment by czietz** [comment]
@AdamKlob : Any updates?
