### ISSUE TITLE
ExtenDOS does not work with emutos

### ISSUE THREAD

**Issue by shift838** [emutos/emutos#39]
I have the latest version of emutos as well as the latest version of ExtenDOS.

When running EMUTOS it loads perfectly but does not allow to use ExtenDOS to see my IDE DVD-RW drive.  my standard TOS 2.06 works fine and sees it, so i know there are no issues with the hardware.

Does EMUTOS not work with ExtenDOS?

![IMG_1303](https://user-images.githubusercontent.com/18707871/234623454-a95e9518-f8af-4f41-bb63-3dbf47a95430.JPG)
![IMG_1304](https://user-images.githubusercontent.com/18707871/234623486-1fbe9b4b-39da-46b1-860c-3cc2023b3de0.JPG)

**Comment by czietz** [comment]
Thank you for your report.

First of all, I can confirm that there is no incompatibility between ExtenDOS and EmuTOS in general. For example, I use ExtenDOS with my USB CD drive under EmuTOS.

However, in your case there is an issue that is at least indirectly related to EmuTOS. To use an IDE CD drive, ExtenDOS requires a driver that exposes a SCSIDRV interface to third-party applications. (The SCSIDRV interface basically allows ExtenDOS to talk to the IDE drive as if it was a SCSI CD drive.)

I suppose that under TOS 2.06 you boot HDDRIVER from your hard disk, which then provides the SCSIDRV interface to ExtenDOS. EmuTOS, on the other hand, does not boot HDDRIVER, as it comes with its own hard disk driver. But EmuTOS does not provide a SCSIDRV interface (at the time of this writing).

I have not tested it, but I wonder if would work if you configured HDDRIVER to _only_ take care of your CD drive (and to leave the hard disk to EmuTOS's driver) and then loaded HDDRIVER before ExtenDOS.

**Comment by czietz** [comment]
Starting with commit 2fff4960 EmuTOS now has a SCSIDRV interface that supports ACSI, SCSI and IDE drives.

In particular, this makes it possible to use ExtenDOS directly under EmuTOS without the help of a 3rd party hard disk driver. You can try this by using EmuTOS snapshot 20230716-201213-2fff4960 or any newer snapshot: https://sourceforge.net/projects/emutos/files/snapshots.
