### ISSUE TITLE
Update Vampire V2

### ISSUE THREAD

**Issue by coriolis1986** [emutos/emutos#40]
Hi all.

I see that currect state of a project allows to build Vamipre V2 version of EmuTOS.

V2 accelerators already have EmuTOS in their cores. So, I think, there should be a way to update EmuTOS in V2 without erasing Amiga Kickstart image.

Do anyone knows how to do it?

**Comment by czietz** [comment]
The integration of EmuTOS into the Vampire cores is done by the Vampire developers, hence your question might be better addressed to them.

I can only answer this for the Vampire V**4**, but perhaps similar solutions exist for the V2: On the V4SA you can temporarily (i.e., without flashing) load a new EmuTOS ROM image with with "maprom" tools such as https://github.com/agranlund/v4map. There is also a flashing tool that allows to permanently replace the ROM that is included with the core. Maybe @shoggoth77 knows if a similar flashing tool exists for the V2, too.

**Comment by czietz** [comment]
Closing this due to lack of updates. Probably, this question is better discussed at a Vampire discussion forum.
