### ISSUE TITLE
Enhancement: Allow for aspect ratio correction

### ISSUE THREAD

**Issue by thedocbwarren** [emutos/emutos#43]
I think it would be a nice improvement for TOS apps to run correctly in 640x200 resolutions.  Meaning no longer stretching the UI so much as it's incorrect for the tall pixels.  At the very least allow for swapping some elements for more tuned icons, window decorations, lines, borders, etc.

Icons are too tall, windows and dialogs look horrible with thicker lines on top due to tall pixels, fonts look terrible and don't correctly render, etc.

**Comment by th-otto** [comment]
That is a well known shortcoming of the strange aspect ratio of a 640x200 
resolution. Most applications will already handle this by prividing different 
set of icons for that resolution, if needed. Doing that automatically (however 
that should work) will most likely break those apps.

What exactly do you have in mind, how should that be handled?

**Comment by czietz** [comment]
Thank you for your contribution!

However, I'm not 100% certain I understand. In my opinion, EmuTOS in ST medium (640x200) does not look significantly different than Atari TOS in the same resolution. And this is required for compatibility. Any changes in the aspect ratio or scaling of AES elements is bound to break a lot of existing programs.

**Comment by thedocbwarren** [comment]
> That is a well known shortcoming of the strange aspect ratio of a 640x200 resolution. Most applications will already handle this by providing different set of icons for that resolution, if needed. Doing that automatically (however that should work) will most likely break those apps. What exactly do you have in mind, how should that be handled?

However true, I'm considering the general experience to fix some of these issues in a way that won't break that compatibility for most cases.  What I'm considering is drawing a few of the window items better that fit nicely in the Tall pixel aspect.  Some of these are simple cleaner icons, and less dense lines for horizontal lines pained.  Maybe some better, hand crafted, areas of the UI can make for a nicer desktop as well.  I think this should be optional as it could change look and feel here and there.  More than happy to mock something.  I'm a c developer as well and may have some ability to help if needed.

**Comment by thedocbwarren** [comment]
> Thank you for your contribution!
> 
> However, I'm not 100% certain I understand. In my opinion, EmuTOS in ST medium (640x200) does not look significantly different than Atari TOS in the same resolution. And this is required for compatibility. Any changes in the aspect ratio or scaling of AES elements is bound to break a lot of existing programs.

That's the issue!  :) Wanting to improve the 200 vertical pixel experience.  That is the majority of the users in the ST space running GEM apps not in an emulator or in native resolutions with non-square pixels.

**Comment by czietz** [comment]
I'm still quite skeptical how this could be achieved without breaking a lot of applications. But I'm of course open to be surprised / proven wrong 😃. 

Not (deliberately) breaking compatibility with Atari TOS is one of the key design goals of EmuTOS. 

Be aware, though, that for the ST we have to support 192k ROMs, which only have very few kiB free space left. If you want to make your proposed change optional at runtime (and not at compile time), it would have to fit very little ROM space.

**Comment by thedocbwarren** [comment]
> I'm still quite skeptical how this could be achieved without breaking a lot of applications. But I'm of course open to be surprised / proven wrong 😃.
> 
> Not (deliberately) breaking compatibility with Atari TOS is one of the key design goals of EmuTOS.
> 
> Be aware, though, that for the ST we have to support 192k ROMs, which only have very few kiB free space left. If you want to make your proposed change optional at runtime (and not at compile time), it would have to fit very little ROM space.

All sounds good, I'll mock something.

**Comment by thedocbwarren** [comment]
My thoughts are this, changing the rendering of the dialog and icons without changing scaling or what they render so much as to break the apps but have them look better in Medium res.  Can be done as I used to hack this is some apps I wrote a long time ago to use Medium like it was high res (like the Apple IIgs did in GS/OS.)  I noticed EMUTOS already themed a bit so I think this could be a theme (opt-in) thing.  This would especially be so for in RAM version since ROMs are a bit impractical for most as it might change too much to be worth burning a ROM.  Anyway I'll mock a desktop and a few pics to show what I mean.

**Comment by vinriviere** [comment]
> Allow for aspect ratio correction

Ah, huge topic! AFAIK Atari TOS hasn't support for pixel aspect ratio (or maybe GDOS for printers?). So it would be difficult to do something without breaking compatibility.

But I agree, medium resolution is ugly. Specially, squashed icons. And even mouse cursor. That shocked me from day 1.

> I think it would be a nice improvement for TOS apps to run correctly in 640x200 resolutions. Meaning no longer stretching the UI so much as it's incorrect for the tall pixels.

As a hack, to see what happens:

- Dialogs could be dynamically stretched horizontally in medium resolution, so they look less squashed. But the font will keep the same size, so the result may look weird.
I don't remember well, but IIRC dialogs height is already automatically adjusted so they have more or less the same aspect in medium or high resolutions (but bitmaps aren't adjusted).

- EmuDesk could be patched to use a different icon set in medium resolution, so they look less squashed. But the icon size won't change, so the result might look weird again.

I don't think that any of those ideas would be suitable for official EmuTOS. But feel free to give a try. I'm curious to see how it could look like.

**Comment by thedocbwarren** [comment]
> > Allow for aspect ratio correction
> 
> Ah, huge topic! AFAIK Atari TOS hasn't support for pixel aspect ratio (or maybe GDOS for printers?). So it would be difficult to do something without breaking compatibility.
> 
> But I agree, medium resolution is ugly. Specially, squashed icons. And even mouse cursor. That shocked me from day 1.
> 
> > I think it would be a nice improvement for TOS apps to run correctly in 640x200 resolutions. Meaning no longer stretching the UI so much as it's incorrect for the tall pixels.
> 
> As a hack, to see what happens:
> 
> * Dialogs could be dynamically stretched horizontally in medium resolution, so they look less squashed. But the font will keep the same size, so the result may look weird.
>   I don't remember well, but IIRC dialogs height is already automatically adjusted so they have more or less the same aspect in medium or high resolutions (but bitmaps aren't adjusted).
> * EmuDesk could be patched to use a different icon set in medium resolution, so they look less squashed. But the icon size won't change, so the result might look weird again.
> 
> I don't think that any of those ideas would be suitable for official EmuTOS. But feel free to give a try. I'm curious to see how it could look like.

Don't think I disagree on the official, but I'm planning on trying to give an optional medium res rescale for use in RAM.  I did this kind of thing in NeoDesk years ago and it made it look like a color Mac.  Looks very nice and intentional.  

Given this is all moot for real world and I think the thought was it goes away some day anyway with higher res and later models.  However, for use today with the idea you use medium to run a few things, I like the idea of fixing this not assuming you upgrade the machine with new graphics modes.

**Comment by czietz** [comment]
Closing this after three months without updates. Feel free to reopen, if you are still working on this. (But note Vincent's and my comments about not breaking compatibility with Atari TOS.)
