### ISSUE TITLE
Wrong clamp of signed value

### ISSUE THREAD

**Issue by th-otto** [emutos/emutos#50]
I don't think that anyone will use such insane values, but

https://github.com/emutos/emutos/blob/aca309207086d913a9246af061023c98b24fafd5/aes/gemobjop.c#L68-L69

should imho read `>=` to clamp a signed value to the correct range.

(that code is original from DRI sources, and also present in TOS)

**Comment by czietz** [comment]
At first glance it's not clear to me what this code is supposed to do. Why does "th" need to be clamped to a signed char? What do negative values even mean? Maybe we should discuss this on the mailing list.

**Comment by th-otto** [comment]
"th" is the value of the framesize of the obspec for BOX/IBOX/BOXCHAR and should be treated as signed, because negative values specify a frame drawn toward the outside, and positive values toward the inside of the object.

However most resource editors only allow specifying a value of in the range -4 to 4.

Everything else would look rather strange, like here with a framesize of -16:
![Screenshot_20240905_083104](https://github.com/user-attachments/assets/650e7dfb-4ce7-4f07-a172-80b6a600ed14)

**Comment by czietz** [comment]
I have checked the _GEM Programmer's Guide Volume 2 - AES_. It specifically documents that a thickness of 128 is to be drawn inside:

![grafik](https://github.com/user-attachments/assets/ba76b697-1a99-4a5e-9ca7-14bed3b1d0c1)

While I agree with you that probably no meaningful program is using such an extreme value, I still find that EmuTOS should stay true to the AES documentation (and Atari's implementation).

**Comment by th-otto** [comment]
Thanks for checking this. Its a bit strange to treat 128 as positive when read from a byte, but well...

**Comment by czietz** [comment]
> Thanks for checking this. Its a bit strange to treat 128 as positive when read from a byte, but well...

Yes, we might speculate that the original intentions were different, the author made an error, and that this deviation was only documented after the fact. But that would be mere speculation...

**Comment by vinriviere** [comment]
> I have checked the GEM Programmer's Guide Volume 2 - AES. It specifically documents that a thickness of 128 is to be drawn inside:

Excellent discovery!

> While I agree with you that probably no meaningful program is using such an extreme value, I still find that EmuTOS should stay true to the AES documentation (and Atari's implementation).

Alas, we know the rule: TOS is always right, even when it's strange (or wrong). Here the behaviour is even officially documented. So we have no other choice than doing the same.
