### ISSUE TITLE
Bad color for G_IMAGE when Blitter is active ?

### ISSUE THREAD

**Issue by Daroou** [emutos/emutos#7]
Hi,

I have 2 G_IMAGE in my RSC (of color 9 (dark gray)) which appears red when the blitter is active.
The G_IMAGE are displayed by objc_draw() (In their form)

![blitter_on](https://user-images.githubusercontent.com/25867137/29680650-8841e47a-8905-11e7-995f-a58120ba0fbc.png)
Blitter active

![blitteroff](https://user-images.githubusercontent.com/25867137/29680687-a25c7d5c-8905-11e7-8baa-45418288db71.png)
Blitter off

Tested with snapshot 2017-07-10 and 2017-08-24 (**Hatari**  (mega) STe / Falcon)

(Sorry for web translation)

**Comment by anodynesoftware** [comment]
We're not really set up to use the issue tracker for EmuTOS problems.  Please report this on the EmuTOS mailing list, where it's more convenient for me to request further info, and I can get help from other developers.

**Comment by anodynesoftware** [comment]
This should now (at long last) be fixed by commit 9712bcb. Sorry for the extreme delay, and thank you for reporting this. For some reason, I thought we'd fixed this long ago.
